---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: localhost
  requirements_path: requirements-test.txt
  group_vars_path: group-vars
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_vault_password_file: <%= ENV['HOME'] %>/.ansible/vault_pass.txt

platforms:
  - name: centos-6.7
  - name: centos-7.1

verifier:
  format: ['progress', 'documentation']
  additional_install_command: sudo sed -i "s/Defaults.*secure_path\(.*\)/Defaults secure_path\1:\/usr\/local\/sbin:\/usr\/local\/bin/" /etc/sudoers

suites:
  - name: default
    excludes: ['centos-7.1']
    provisioner:
      name: ansible_playbook
      playbook: test.yml
      additional_copy_path:
        - "."

